package com.atiurin.ultron.core.compose

import com.atiurin.ultron.core.common.UltronOperationType

enum class ComposeOperationType : UltronOperationType {
    CLICK, LONG_CLICK, DOUBLE_CLICK,
    TYPE_TEXT, REPLACE_TEXT, CLEAR_TEXT, PRESS_KEY,
    SWIPE_LEFT, SWIPE_RIGHT, SWIPE_UP, SWIPE_DOWN, SCROLL, CUSTOM,
    CLOSE_SOFT_KEYBOARD, PRESS_BACK,
    IS_DISPLAYED, IS_NOT_DISPLAYED, IS_COMPLETELY_DISPLAYED, IS_DISPLAYING_AT_LEAST,
    DOES_NOT_EXIST, EXISTS,
    IS_ENABLED, IS_NOT_ENABLED,
    IS_SELECTED, IS_NOT_SELECTED, IS_SELECTABLE,
    IS_CLICKABLE, IS_NOT_CLICKABLE,
    IS_CHECKED, IS_NOT_CHECKED,
    IS_FOCUSED, IS_NOT_FOCUSED,
    IS_ON, IS_OFF,
    HAS_CLICK_ACTION, HAS_NO_CLICK_ACTION,
    TEXT_EQUALS, CONTAINS_TEXT,
    HAS_CONTENT_DESCRIPTION, CONTENT_DESCRIPTION_CONTAINS_TEXT,
    ASSERT_MATCHES,
    GET_TEXT
}